from typing import Dict
import Levenshtein
from pydantic import BaseModel


class LinguisticMetrics(BaseModel):
    """Validated structure for advanced linguistic metrics."""
    levenshtein_dist: int
    semantic_overlap: float
    expansion_ratio: float
    ms_per_word: float
    punc_density: float
    word_count: int
    unique_ratio: float


def calculate_advanced_linguistic_metrics(
    input_text: str,
    output_text: str,
    duration_ms: float
) -> LinguisticMetrics:
    """
    Calculates advanced linguistic and NLP metrics to evaluate the quality of
    transformations performed by large language models (LLMs).

    Main Description
    ----------------
    This function compares an input text and its transformed output to compute
    several technical metrics. These metrics are useful for assessing semantic
    fidelity, linguistic diversity, and efficiency of generated responses.

    References
    ----------
    - Levenshtein distance: https://en.wikipedia.org/wiki/Levenshtein_distance
    - Jaccard similarity: https://en.wikipedia.org/wiki/Jaccard_index
    - Vocabulary diversity: https://en.wikipedia.org/wiki/Lexical_diversity
    - Text expansion ratio: https://aclanthology.org/W19-4304/
    - Punctuation density: https://www.sciencedirect.com/science/article/pii/S1877042814037987

    Parameters
    ----------
    input_text : str
        Original text before transformation.
    output_text : str
        Transformed text generated by the LLM.
    duration_ms : float
        Processing duration in milliseconds, used to calculate velocity metrics.

    Returns
    -------
    LinguisticMetrics
        Structured metrics object with validated fields.

    Other Staff
    -----------
    - Defensive programming ensures inputs are coerced to strings.
    - Handles division by zero gracefully using `max(1, count)` guards.
    - Metrics are rounded to two decimal places for readability.
    - Ready for JSONL serialization via `.model_dump()`.
    """
    input_text = str(input_text or "")
    output_text = str(output_text or "")

    input_words = set(input_text.lower().split())
    output_words = output_text.lower().split()
    output_set = set(output_words)

    word_count = len(output_words)
    input_count = len(input_words)

    try:
        edit_dist = Levenshtein.distance(input_text, output_text)
    except Exception:
        edit_dist = -1  # fallback if library fails

    intersection = input_words.intersection(output_set)
    union = input_words.union(output_set)
    jaccard_score = round(len(intersection) / len(union), 2) if union else 1.0

    expansion_ratio = round(word_count / max(1, input_count), 2)
    ms_per_word = round(duration_ms / max(1, word_count), 2)

    punc_count = sum(1 for char in output_text if char in ".,!?;:-")
    punc_density = round(punc_count / max(1, word_count), 2)

    unique_ratio = round(len(output_set) / max(1, word_count), 2)

    return LinguisticMetrics(
        levenshtein_dist=edit_dist,
        semantic_overlap=jaccard_score,
        expansion_ratio=expansion_ratio,
        ms_per_word=ms_per_word,
        punc_density=punc_density,
        word_count=word_count,
        unique_ratio=unique_ratio
    )
